name: PR Validation - Full Test Suite

on:
  pull_request:
    branches: [ main ]

jobs:
  unit-tests:
    name: Unit Tests (Linux)
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run unit tests
      run: npm test

    - name: Generate coverage report
      run: npm test -- --coverage
      continue-on-error: true

    - name: Upload coverage
      uses: actions/upload-artifact@v4
      if: matrix.node-version == '20.x'
      with:
        name: coverage-report
        path: coverage/
        retention-days: 7

  e2e-tests:
    name: E2E Tests (macOS)
    runs-on: macos-latest
    needs: unit-tests

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright browsers
      run: npx playwright install --with-deps

    - name: Run E2E tests
      run: npm run test:e2e

    - name: Upload test results on failure
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: playwright-report
        path: test-results/playwright-report/
        retention-days: 7
